name: Claude API Test

on:
  workflow_dispatch:  # 手動起動

jobs:
  claude_post:
    runs-on: ubuntu-latest
    steps:
      - name: Run Claude API request via curl
        run: |
          curl -X POST "https://api.anthropic.com/v1/messages" \
            -H "Authorization: Bearer ${{ secrets.ANTHROPIC_API_KEY_GOTS_YAHOO }}" \
            -H "Content-Type: application/json" \
            -H "anthropic-version: 2023-06-01" \
            -d '{
              "model": "claude-3-haiku-20240307",
              "max_tokens": 5,
              "messages": [{"role": "user", "content": "Hi"}]
            }'
