curl -X POST "https://api.anthropic.com/v1/messages" \
  -H "Authorization: Bearer sk-ant-api03-J8E...fQAA" \
  -H "Content-Type: application/json" \
  -H "anthropic-version: 2023-06-01" \
  -d '{
    "model": "claude-3-haiku-20240307",
    "max_tokens": 5,
    "messages": [{"role": "user", "content": "Hi"}]
  }'
